Search.appendIndex(
    [
                {
            "fqsen": "\\Steganography\\BinaryMessage",
            "name": "BinaryMessage",
            "summary": "A\u0020binary\u0020rappresentation\u0020of\u0020Message.",
            "url": "classes/Steganography-BinaryMessage.html"
        },                {
            "fqsen": "\\Steganography\\BinaryMessage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Binary\u0020Message\u0020Construct.",
            "url": "classes/Steganography-BinaryMessage.html#method___construct"
        },                {
            "fqsen": "\\Steganography\\BinaryMessage\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "Returns\u0020the\u0020binary\u0020into\u0020a\u0020string.",
            "url": "classes/Steganography-BinaryMessage.html#method_toString"
        },                {
            "fqsen": "\\Steganography\\BinaryMessage\u003A\u003AgetBinary\u0028\u0029",
            "name": "getBinary",
            "summary": "Returns\u0020the\u0020binary\u0020rappresentation\u0020of\u0020the\u0020string.",
            "url": "classes/Steganography-BinaryMessage.html#method_getBinary"
        },                {
            "fqsen": "\\Steganography\\BinaryMessage\u003A\u003AaddEOM\u0028\u0029",
            "name": "addEOM",
            "summary": "Adds\u0020the\u0020End\u0020Of\u0020Message\u0020to\u0020the\u0020binary\u0020string.",
            "url": "classes/Steganography-BinaryMessage.html#method_addEOM"
        },                {
            "fqsen": "\\Steganography\\BinaryMessage\u003A\u003AgetLength\u0028\u0029",
            "name": "getLength",
            "summary": "Returns\u0020the\u0020length\u0020of\u0020the\u0020binary\u0020message",
            "url": "classes/Steganography-BinaryMessage.html#method_getLength"
        },                {
            "fqsen": "\\Steganography\\BinaryMessage\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Steganography-BinaryMessage.html#method___toString"
        },                {
            "fqsen": "\\Steganography\\BinaryMessage\u003A\u003ADEFAULT_EOM",
            "name": "DEFAULT_EOM",
            "summary": "",
            "url": "classes/Steganography-BinaryMessage.html#constant_DEFAULT_EOM"
        },                {
            "fqsen": "\\Steganography\\BinaryMessage\u003A\u003A\u0024binary",
            "name": "binary",
            "summary": "",
            "url": "classes/Steganography-BinaryMessage.html#property_binary"
        },                {
            "fqsen": "\\Steganography\\Decoder",
            "name": "Decoder",
            "summary": "Decodes\u0020a\u0020message\u0020from\u0020a\u0020medium.",
            "url": "classes/Steganography-Decoder.html"
        },                {
            "fqsen": "\\Steganography\\Decoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Decoder\u0020constructor.",
            "url": "classes/Steganography-Decoder.html#method___construct"
        },                {
            "fqsen": "\\Steganography\\Decoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "Decodes\u0020the\u0020message\u0020from\u0020the\u0020medium",
            "url": "classes/Steganography-Decoder.html#method_decode"
        },                {
            "fqsen": "\\Steganography\\Decoder\u003A\u003A\u0024src",
            "name": "src",
            "summary": "",
            "url": "classes/Steganography-Decoder.html#property_src"
        },                {
            "fqsen": "\\Steganography\\Decoder\u003A\u003A\u0024eom",
            "name": "eom",
            "summary": "",
            "url": "classes/Steganography-Decoder.html#property_eom"
        },                {
            "fqsen": "\\Steganography\\Encoder",
            "name": "Encoder",
            "summary": "Encodes\u0020a\u0020message\u0020into\u0020a\u0020medium\u0020using\u0020the\u0020LSB\u0020of\u0020each\u0020pixel.",
            "url": "classes/Steganography-Encoder.html"
        },                {
            "fqsen": "\\Steganography\\Encoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Encoder\u0020constructor.",
            "url": "classes/Steganography-Encoder.html#method___construct"
        },                {
            "fqsen": "\\Steganography\\Encoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "Encodes\u0020the\u0020message\u0020into\u0020the\u0020medium.",
            "url": "classes/Steganography-Encoder.html#method_encode"
        },                {
            "fqsen": "\\Steganography\\Encoder\u003A\u003A\u0024src",
            "name": "src",
            "summary": "",
            "url": "classes/Steganography-Encoder.html#property_src"
        },                {
            "fqsen": "\\Steganography\\Encoder\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/Steganography-Encoder.html#property_message"
        },                {
            "fqsen": "\\Steganography\\Encoder\u003A\u003A\u0024eom",
            "name": "eom",
            "summary": "",
            "url": "classes/Steganography-Encoder.html#property_eom"
        },                {
            "fqsen": "\\Steganography\\Exception\\Medium\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Steganography-Exception-Medium-Exception.html"
        },                {
            "fqsen": "\\Steganography\\Exception\\Medium\\Image\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Steganography-Exception-Medium-Image-Exception.html"
        },                {
            "fqsen": "\\Steganography\\Exception\\Message\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Steganography-Exception-Message-Exception.html"
        },                {
            "fqsen": "\\Steganography\\Exception\\Message\\NotFoundException",
            "name": "NotFoundException",
            "summary": "",
            "url": "classes/Steganography-Exception-Message-NotFoundException.html"
        },                {
            "fqsen": "\\Steganography\\Exception\\Message\\TooLongException",
            "name": "TooLongException",
            "summary": "",
            "url": "classes/Steganography-Exception-Message-TooLongException.html"
        },                {
            "fqsen": "\\Steganography\\Exception\\SteganographyException",
            "name": "SteganographyException",
            "summary": "",
            "url": "classes/Steganography-Exception-SteganographyException.html"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image",
            "name": "Image",
            "summary": "Image\u0020rappresentation\u0020of\u0020a\u0020medium",
            "url": "classes/Steganography-Medium-Image-Image.html"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Medium\u0020Constructor.",
            "url": "classes/Steganography-Medium-Image-Image.html#method___construct"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AloadImageInfo\u0028\u0029",
            "name": "loadImageInfo",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#method_loadImageInfo"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AgetImage\u0028\u0029",
            "name": "getImage",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#method_getImage"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AcreateImage\u0028\u0029",
            "name": "createImage",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#method_createImage"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "Returns\u0020the\u0020path\u0020of\u0020the\u0020medium.",
            "url": "classes/Steganography-Medium-Image-Image.html#method_getPath"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AgetWidth\u0028\u0029",
            "name": "getWidth",
            "summary": "Returns\u0020the\u0020width\u0020in\u0020bytes\u0020of\u0020the\u0020medium.",
            "url": "classes/Steganography-Medium-Image-Image.html#method_getWidth"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AgetHeight\u0028\u0029",
            "name": "getHeight",
            "summary": "Returns\u0020the\u0020heigth\u0020in\u0020bytes\u0020of\u0020the\u0020medium.",
            "url": "classes/Steganography-Medium-Image-Image.html#method_getHeight"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#method_getType"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AgetMimetype\u0028\u0029",
            "name": "getMimetype",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#method_getMimetype"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AgetColorAt\u0028\u0029",
            "name": "getColorAt",
            "summary": "Returns\u0020the\u0020index\u0020of\u0020the\u0020color\u0020of\u0020a\u0020pixel.",
            "url": "classes/Steganography-Medium-Image-Image.html#method_getColorAt"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AcolorAllocate\u0028\u0029",
            "name": "colorAllocate",
            "summary": "Allocate\u0020a\u0020color\u0020for\u0020an\u0020image.",
            "url": "classes/Steganography-Medium-Image-Image.html#method_colorAllocate"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AsetPixel\u0028\u0029",
            "name": "setPixel",
            "summary": "Sets\u0020a\u0020single\u0020pixel.",
            "url": "classes/Steganography-Medium-Image-Image.html#method_setPixel"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003AsaveToPath\u0028\u0029",
            "name": "saveToPath",
            "summary": "Saves\u0020the\u0020medium\u0020to\u0020the\u0020specified\u0020path.",
            "url": "classes/Steganography-Medium-Image-Image.html#method_saveToPath"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#method___destruct"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#property_path"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003A\u0024width",
            "name": "width",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#property_width"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003A\u0024height",
            "name": "height",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#property_height"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#property_type"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003A\u0024mimeType",
            "name": "mimeType",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#property_mimeType"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\Image\u003A\u003A\u0024img",
            "name": "img",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-Image.html#property_img"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\JPG",
            "name": "JPG",
            "summary": "Jpeg\u0020rappresentation\u0020of\u0020a\u0020medium.",
            "url": "classes/Steganography-Medium-Image-JPG.html"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\JPG\u003A\u003AcreateImage\u0028\u0029",
            "name": "createImage",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-JPG.html#method_createImage"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\JPG\u003A\u003AsaveToPath\u0028\u0029",
            "name": "saveToPath",
            "summary": "Saves\u0020the\u0020medium\u0020to\u0020the\u0020specified\u0020path.",
            "url": "classes/Steganography-Medium-Image-JPG.html#method_saveToPath"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\PNG",
            "name": "PNG",
            "summary": "PNG\u0020representation\u0020of\u0020a\u0020medium.",
            "url": "classes/Steganography-Medium-Image-PNG.html"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\PNG\u003A\u003AcreateImage\u0028\u0029",
            "name": "createImage",
            "summary": "",
            "url": "classes/Steganography-Medium-Image-PNG.html#method_createImage"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image\\PNG\u003A\u003AsaveToPath\u0028\u0029",
            "name": "saveToPath",
            "summary": "Saves\u0020the\u0020medium\u0020to\u0020the\u0020specified\u0020path.",
            "url": "classes/Steganography-Medium-Image-PNG.html#method_saveToPath"
        },                {
            "fqsen": "\\Steganography\\MediumInterface",
            "name": "MediumInterface",
            "summary": "",
            "url": "classes/Steganography-MediumInterface.html"
        },                {
            "fqsen": "\\Steganography\\MediumInterface\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Medium\u0020Constructor.",
            "url": "classes/Steganography-MediumInterface.html#method___construct"
        },                {
            "fqsen": "\\Steganography\\MediumInterface\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "Returns\u0020the\u0020path\u0020of\u0020the\u0020medium.",
            "url": "classes/Steganography-MediumInterface.html#method_getPath"
        },                {
            "fqsen": "\\Steganography\\MediumInterface\u003A\u003AgetWidth\u0028\u0029",
            "name": "getWidth",
            "summary": "Returns\u0020the\u0020width\u0020in\u0020bytes\u0020of\u0020the\u0020medium.",
            "url": "classes/Steganography-MediumInterface.html#method_getWidth"
        },                {
            "fqsen": "\\Steganography\\MediumInterface\u003A\u003AgetHeight\u0028\u0029",
            "name": "getHeight",
            "summary": "Returns\u0020the\u0020heigth\u0020in\u0020bytes\u0020of\u0020the\u0020medium.",
            "url": "classes/Steganography-MediumInterface.html#method_getHeight"
        },                {
            "fqsen": "\\Steganography\\MediumInterface\u003A\u003AgetColorAt\u0028\u0029",
            "name": "getColorAt",
            "summary": "Returns\u0020the\u0020index\u0020of\u0020the\u0020color\u0020of\u0020a\u0020pixel.",
            "url": "classes/Steganography-MediumInterface.html#method_getColorAt"
        },                {
            "fqsen": "\\Steganography\\MediumInterface\u003A\u003AcolorAllocate\u0028\u0029",
            "name": "colorAllocate",
            "summary": "Allocate\u0020a\u0020color\u0020for\u0020an\u0020image.",
            "url": "classes/Steganography-MediumInterface.html#method_colorAllocate"
        },                {
            "fqsen": "\\Steganography\\MediumInterface\u003A\u003AsetPixel\u0028\u0029",
            "name": "setPixel",
            "summary": "Sets\u0020a\u0020single\u0020pixel.",
            "url": "classes/Steganography-MediumInterface.html#method_setPixel"
        },                {
            "fqsen": "\\Steganography\\MediumInterface\u003A\u003AsaveToPath\u0028\u0029",
            "name": "saveToPath",
            "summary": "Saves\u0020the\u0020medium\u0020to\u0020the\u0020specified\u0020path.",
            "url": "classes/Steganography-MediumInterface.html#method_saveToPath"
        },                {
            "fqsen": "\\Steganography\\Message",
            "name": "Message",
            "summary": "Rappresents\u0020a\u0020message\u0020to\u0020be\u0020converted\u0020to\u0020binary.",
            "url": "classes/Steganography-Message.html"
        },                {
            "fqsen": "\\Steganography\\Message\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Message\u0020constructor.",
            "url": "classes/Steganography-Message.html#method___construct"
        },                {
            "fqsen": "\\Steganography\\Message\u003A\u003AtoBinary\u0028\u0029",
            "name": "toBinary",
            "summary": "Returns\u0020a\u0020binary\u0020rappresentation\u0020of\u0020the\u0020message.",
            "url": "classes/Steganography-Message.html#method_toBinary"
        },                {
            "fqsen": "\\Steganography\\Message\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "Returns\u0020the\u0020message.",
            "url": "classes/Steganography-Message.html#method_getMessage"
        },                {
            "fqsen": "\\Steganography\\Message\u003A\u003AgetLength\u0028\u0029",
            "name": "getLength",
            "summary": "Returns\u0020the\u0020length\u0020of\u0020the\u0020message.",
            "url": "classes/Steganography-Message.html#method_getLength"
        },                {
            "fqsen": "\\Steganography\\Message\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Steganography-Message.html#method___toString"
        },                {
            "fqsen": "\\Steganography\\Message\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/Steganography-Message.html#property_message"
        },                {
            "fqsen": "\\Steganography\\Pixel",
            "name": "Pixel",
            "summary": "Rappresents\u0020a\u0020Pixel\u0020inside\u0020a\u0020medium.",
            "url": "classes/Steganography-Pixel.html"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Pixel\u0020constructor.",
            "url": "classes/Steganography-Pixel.html#method___construct"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003AgetX\u0028\u0029",
            "name": "getX",
            "summary": "Returns\u0020the\u0020X\u0020coordinate\u0020of\u0020the\u0020pixel.",
            "url": "classes/Steganography-Pixel.html#method_getX"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003AgetY\u0028\u0029",
            "name": "getY",
            "summary": "Returns\u0020the\u0020Y\u0020coordinate\u0020of\u0020the\u0020pixel.",
            "url": "classes/Steganography-Pixel.html#method_getY"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003AsetX\u0028\u0029",
            "name": "setX",
            "summary": "Sets\u0020the\u0020X\u0020coordinate.",
            "url": "classes/Steganography-Pixel.html#method_setX"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003AsetY\u0028\u0029",
            "name": "setY",
            "summary": "Sets\u0020the\u0020Y\u0020coordinate.",
            "url": "classes/Steganography-Pixel.html#method_setY"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003AincrX\u0028\u0029",
            "name": "incrX",
            "summary": "Increases\u0020the\u0020X\u0020coordinate",
            "url": "classes/Steganography-Pixel.html#method_incrX"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003AincrY\u0028\u0029",
            "name": "incrY",
            "summary": "Increases\u0020the\u0020Y\u0020coordinate",
            "url": "classes/Steganography-Pixel.html#method_incrY"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003A\u0024x",
            "name": "x",
            "summary": "",
            "url": "classes/Steganography-Pixel.html#property_x"
        },                {
            "fqsen": "\\Steganography\\Pixel\u003A\u003A\u0024y",
            "name": "y",
            "summary": "",
            "url": "classes/Steganography-Pixel.html#property_y"
        },                {
            "fqsen": "\\Steganography\\RGBColor",
            "name": "RGBColor",
            "summary": "Represents\u0020an\u0020RGB\u0020color.",
            "url": "classes/Steganography-RGBColor.html"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Steganography-RGBColor.html#method___construct"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003AgetRgb\u0028\u0029",
            "name": "getRgb",
            "summary": "Returns\u0020the\u0020RGB\u0020value",
            "url": "classes/Steganography-RGBColor.html#method_getRgb"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003AgetRed\u0028\u0029",
            "name": "getRed",
            "summary": "Returns\u0020the\u0020red\u0020value.",
            "url": "classes/Steganography-RGBColor.html#method_getRed"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003AgetGreen\u0028\u0029",
            "name": "getGreen",
            "summary": "Returns\u0020the\u0020green\u0020value.",
            "url": "classes/Steganography-RGBColor.html#method_getGreen"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003AgetBlue\u0028\u0029",
            "name": "getBlue",
            "summary": "Returns\u0020the\u0020blue\u0020value.",
            "url": "classes/Steganography-RGBColor.html#method_getBlue"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003AsetRed\u0028\u0029",
            "name": "setRed",
            "summary": "Sets\u0020the\u0020red\u0020value.",
            "url": "classes/Steganography-RGBColor.html#method_setRed"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003AsetGreen\u0028\u0029",
            "name": "setGreen",
            "summary": "Sets\u0020the\u0020green\u0020value.",
            "url": "classes/Steganography-RGBColor.html#method_setGreen"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003AsetBlue\u0028\u0029",
            "name": "setBlue",
            "summary": "Sets\u0020the\u0020blue\u0020value.",
            "url": "classes/Steganography-RGBColor.html#method_setBlue"
        },                {
            "fqsen": "\\Steganography\\RGBColor\u003A\u003A\u0024rgb",
            "name": "rgb",
            "summary": "",
            "url": "classes/Steganography-RGBColor.html#property_rgb"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Steganography",
            "name": "Steganography",
            "summary": "",
            "url": "namespaces/steganography.html"
        },                {
            "fqsen": "\\Steganography\\Exception\\Medium",
            "name": "Medium",
            "summary": "",
            "url": "namespaces/steganography-exception-medium.html"
        },                {
            "fqsen": "\\Steganography\\Exception\\Medium\\Image",
            "name": "Image",
            "summary": "",
            "url": "namespaces/steganography-exception-medium-image.html"
        },                {
            "fqsen": "\\Steganography\\Exception\\Message",
            "name": "Message",
            "summary": "",
            "url": "namespaces/steganography-exception-message.html"
        },                {
            "fqsen": "\\Steganography\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/steganography-exception.html"
        },                {
            "fqsen": "\\Steganography\\Medium\\Image",
            "name": "Image",
            "summary": "",
            "url": "namespaces/steganography-medium-image.html"
        },                {
            "fqsen": "\\Steganography\\Medium",
            "name": "Medium",
            "summary": "",
            "url": "namespaces/steganography-medium.html"
        }            ]
);
